feat : add lint-staged

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,7 @@
-yarn check-all
+echo 'Styling ,testing and building project before committing.'
+
+yarn lint-staged || (
+    echo 'Failed lint-staged check. Make the required changes listed above, add changes and try to commit again.'
+    false;
+
+)
